
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class StoredProcedureFactory : acr.StoredProcedureFactoryBase< ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		public int CodegenTestStoredProcVarmaxUnicodeTest
		(
			sds.SqlConnection connˡ, 
			scg.List<MyVarmaxUnicodeTableType1٠tt> myudt1, 
			scg.List<MyVarmaxUnicodeTableType2٠tt> myudt2, 
			scg.List<MyVarmaxUnicodeTableType3٠tt> myudt3, 
			scg.List<MyVarmaxUnicodeTableType4٠tt> myudt4, 
			out scg.List<CodegenTestStoredProcVarmaxUnicodeTest٠rs1> rsˡ1, 
			sds.SqlTransaction tranˡ = null
		)
		{
			const string schemaˡ = "dbo" ; 
			const string spˡ = "CodegenTestStoredProcVarmaxUnicodeTest" ; 
			 
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>() ;
			sds.SqlParameter paramˡmyudt1 = base.AddParameterTableTypeˡ( parametersˡ, "@myudt1", this.CodegenTestStoredProcVarmaxUnicodeTest٠myudt1ˡ( myudt1 ), "dbo.MyVarmaxUnicodeTableType1" ) ; 
			sds.SqlParameter paramˡmyudt2 = base.AddParameterTableTypeˡ( parametersˡ, "@myudt2", this.CodegenTestStoredProcVarmaxUnicodeTest٠myudt2ˡ( myudt2 ), "dbo.MyVarmaxUnicodeTableType2" ) ; 
			sds.SqlParameter paramˡmyudt3 = base.AddParameterTableTypeˡ( parametersˡ, "@myudt3", this.CodegenTestStoredProcVarmaxUnicodeTest٠myudt3ˡ( myudt3 ), "dbo.MyVarmaxUnicodeTableType3" ) ; 
			sds.SqlParameter paramˡmyudt4 = base.AddParameterTableTypeˡ( parametersˡ, "@myudt4", this.CodegenTestStoredProcVarmaxUnicodeTest٠myudt4ˡ( myudt4 ), "dbo.MyVarmaxUnicodeTableType4" ) ; 
			sds.SqlParameter paramˡrcˡ = base.AddParameterReturnValueˡ( parametersˡ, "@rcˡ" ) ; 
			 
			sd.DataSet dsˡ = base.Executeˡ( connˡ, tranˡ, schemaˡ, spˡ, parametersˡ ) ;
			 
			rsˡ1 = base.ToRecordsetˡ<CodegenTestStoredProcVarmaxUnicodeTest٠rs1>( dsˡ, 1 ) ;
			 
			return base.GetParameterValueˡ<int>( paramˡrcˡ ) ;
		}
		 
		protected object CodegenTestStoredProcVarmaxUnicodeTest٠myudt1ˡ( scg.List<MyVarmaxUnicodeTableType1٠tt> list )
		{
			if ( list == null ) return null ;
			if ( list.Count == 0 ) return null ;
			return new  ns.storedProcedure.MyVarmaxUnicodeTableType1٠ttlist( list ) ;
		}
		 
		protected object CodegenTestStoredProcVarmaxUnicodeTest٠myudt2ˡ( scg.List<MyVarmaxUnicodeTableType2٠tt> list )
		{
			if ( list == null ) return null ;
			if ( list.Count == 0 ) return null ;
			return new  ns.storedProcedure.MyVarmaxUnicodeTableType2٠ttlist( list ) ;
		}
		 
		protected object CodegenTestStoredProcVarmaxUnicodeTest٠myudt3ˡ( scg.List<MyVarmaxUnicodeTableType3٠tt> list )
		{
			if ( list == null ) return null ;
			if ( list.Count == 0 ) return null ;
			return new  ns.storedProcedure.MyVarmaxUnicodeTableType3٠ttlist( list ) ;
		}
		 
		protected object CodegenTestStoredProcVarmaxUnicodeTest٠myudt4ˡ( scg.List<MyVarmaxUnicodeTableType4٠tt> list )
		{
			if ( list == null ) return null ;
			if ( list.Count == 0 ) return null ;
			return new  ns.storedProcedure.MyVarmaxUnicodeTableType4٠ttlist( list ) ;
		}
	}

}

