
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class CodegenTestFourResultSets٠rs4 : acr.RowBase
	{
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠CustomerID  = "CustomerID" ;
		public const string column٠EmployeeID  = "EmployeeID" ;
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CustomerID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? EmployeeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠EmployeeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠EmployeeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public CodegenTestFourResultSets٠rs4() : base()
		{
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠CustomerID ] = null ;
			base._dicˡ[ column٠EmployeeID ] = null ;
		 
		}

	}

}

