
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class StoredProcedureFactory : acr.StoredProcedureFactoryBase< ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		public int CodegenTestMathParameters
		(
			sds.SqlConnection connˡ, 
			long? a, 
			long? b, 
			ref long? difference, 
			ref long? product, 
			ref long? quotient, 
			sds.SqlTransaction tranˡ = null
		)
		{
			const string schemaˡ = "dbo" ; 
			const string spˡ = "CodegenTestMathParameters" ; 
			 
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>() ;
			sds.SqlParameter paramˡa = base.AddParameterˡ( parametersˡ, "@a", a, sd.SqlDbType.BigInt, true, null, 19, 0 ) ; 
			sds.SqlParameter paramˡb = base.AddParameterˡ( parametersˡ, "@b", b, sd.SqlDbType.BigInt, true, null, 19, 0 ) ; 
			sds.SqlParameter paramˡdifference = base.AddParameterˡ( parametersˡ, "@difference", difference, sd.SqlDbType.BigInt, false, null, 19, 0 ) ; 
			sds.SqlParameter paramˡproduct = base.AddParameterˡ( parametersˡ, "@product", product, sd.SqlDbType.BigInt, false, null, 19, 0 ) ; 
			sds.SqlParameter paramˡquotient = base.AddParameterˡ( parametersˡ, "@quotient", quotient, sd.SqlDbType.BigInt, false, null, 19, 0 ) ; 
			sds.SqlParameter paramˡrcˡ = base.AddParameterReturnValueˡ( parametersˡ, "@rcˡ" ) ; 
			 
			sd.DataSet dsˡ = base.Executeˡ( connˡ, tranˡ, schemaˡ, spˡ, parametersˡ ) ;
			 
			difference = base.GetParameterValueˡ<long?>( paramˡdifference ) ;
			product = base.GetParameterValueˡ<long?>( paramˡproduct ) ;
			quotient = base.GetParameterValueˡ<long?>( paramˡquotient ) ;
			return base.GetParameterValueˡ<int>( paramˡrcˡ ) ;
		}
	}

}

