
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class StoredProcedureFactory : acr.StoredProcedureFactoryBase< ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		public int CodegenTestFourResultSets
		(
			sds.SqlConnection connˡ, 
			int? orderID, 
			out scg.List<CodegenTestFourResultSets٠rs1> rsˡ1, 
			out scg.List<CodegenTestFourResultSets٠rs2> rsˡ2, 
			out scg.List<CodegenTestFourResultSets٠rs3> rsˡ3, 
			out scg.List<CodegenTestFourResultSets٠rs4> rsˡ4, 
			sds.SqlTransaction tranˡ = null
		)
		{
			const string schemaˡ = "dbo" ; 
			const string spˡ = "CodegenTestFourResultSets" ; 
			 
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>() ;
			sds.SqlParameter paramˡorderID = base.AddParameterˡ( parametersˡ, "@orderID", orderID, sd.SqlDbType.Int, true, null, 10, 0 ) ; 
			sds.SqlParameter paramˡrcˡ = base.AddParameterReturnValueˡ( parametersˡ, "@rcˡ" ) ; 
			 
			sd.DataSet dsˡ = base.Executeˡ( connˡ, tranˡ, schemaˡ, spˡ, parametersˡ ) ;
			 
			rsˡ1 = base.ToRecordsetˡ<CodegenTestFourResultSets٠rs1>( dsˡ, 1 ) ;
			rsˡ2 = base.ToRecordsetˡ<CodegenTestFourResultSets٠rs2>( dsˡ, 2 ) ;
			rsˡ3 = base.ToRecordsetˡ<CodegenTestFourResultSets٠rs3>( dsˡ, 3 ) ;
			rsˡ4 = base.ToRecordsetˡ<CodegenTestFourResultSets٠rs4>( dsˡ, 4 ) ;
			 
			return base.GetParameterValueˡ<int>( paramˡrcˡ ) ;
		}
	}

}

