
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class CustOrdersDetail٠rs1 : acr.RowBase
	{
		public const string column٠ProductName  = "ProductName" ;
		public const string column٠UnitPrice  = "UnitPrice" ;
		public const string column٠Quantity  = "Quantity" ;
		public const string column٠Discount  = "Discount" ;
		public const string column٠ExtendedPrice  = "ExtendedPrice" ;
		 
		public string ProductName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ProductName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ProductName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? UnitPrice
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠UnitPrice ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠UnitPrice, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public short? Quantity
		{
			get
			{
				return base.GetValueˡ<short?>( _dicˡ, column٠Quantity ) ; 
			}
			set
			{
				base.SetValueˡ<short?>( _dicˡ, column٠Quantity, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? Discount
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠Discount ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠Discount, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? ExtendedPrice
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠ExtendedPrice ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠ExtendedPrice, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public CustOrdersDetail٠rs1() : base()
		{
			base._dicˡ[ column٠ProductName ] = null ;
			base._dicˡ[ column٠UnitPrice ] = null ;
			base._dicˡ[ column٠Quantity ] = null ;
			base._dicˡ[ column٠Discount ] = null ;
			base._dicˡ[ column٠ExtendedPrice ] = null ;
		 
		}

	}

}

