
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class MyPrecisonScaleTableType٠tt : acr.RowBase
	{
		public const string column٠TheMoney  = "TheMoney" ;
		public const string column٠TheSmallMoney  = "TheSmallMoney" ;
		public const string column٠TheDecimal0  = "TheDecimal0" ;
		public const string column٠TheDecimal1  = "TheDecimal1" ;
		public const string column٠TheDecimal2  = "TheDecimal2" ;
		public const string column٠TheNumeric0  = "TheNumeric0" ;
		public const string column٠TheNumeric1  = "TheNumeric1" ;
		public const string column٠TheNumeric2  = "TheNumeric2" ;
		 
		public decimal? TheMoney
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheMoney ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheMoney, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheSmallMoney
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheSmallMoney ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheSmallMoney, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheDecimal0
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheDecimal0 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheDecimal0, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheDecimal1
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheDecimal1 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheDecimal1, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheDecimal2
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheDecimal2 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheDecimal2, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheNumeric0
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheNumeric0 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheNumeric0, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheNumeric1
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheNumeric1 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheNumeric1, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? TheNumeric2
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠TheNumeric2 ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠TheNumeric2, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public MyPrecisonScaleTableType٠tt() : base()
		{
			base._dicˡ[ column٠TheMoney ] = null ;
			base._dicˡ[ column٠TheSmallMoney ] = null ;
			base._dicˡ[ column٠TheDecimal0 ] = null ;
			base._dicˡ[ column٠TheDecimal1 ] = null ;
			base._dicˡ[ column٠TheDecimal2 ] = null ;
			base._dicˡ[ column٠TheNumeric0 ] = null ;
			base._dicˡ[ column٠TheNumeric1 ] = null ;
			base._dicˡ[ column٠TheNumeric2 ] = null ;
		 
		}

	}

}

