
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class MyPrecisonScaleTableType٠ttlist : scg.List< MyPrecisonScaleTableType٠tt >, scg.IEnumerable< mss.SqlDataRecord >
	{
		scg.List< MyPrecisonScaleTableType٠tt > _list = null ;
		 
		public MyPrecisonScaleTableType٠ttlist( scg.List< MyPrecisonScaleTableType٠tt > list )
		{
			_list = list ;
		}
		 
		scg.IEnumerator< mss.SqlDataRecord > scg.IEnumerable< mss.SqlDataRecord >.GetEnumerator()
		{
			var sdr = new mss.SqlDataRecord
			(
				new mss.SqlMetaData( "TheMoney", sd.SqlDbType.Money ) ,
				new mss.SqlMetaData( "TheSmallMoney", sd.SqlDbType.SmallMoney ) ,
				new mss.SqlMetaData( "TheDecimal0", sd.SqlDbType.Decimal, 18, 0 ) ,
				new mss.SqlMetaData( "TheDecimal1", sd.SqlDbType.Decimal, 29, 28 ) ,
				new mss.SqlMetaData( "TheDecimal2", sd.SqlDbType.Decimal, 38, 1 ) ,
				new mss.SqlMetaData( "TheNumeric0", sd.SqlDbType.Decimal, 18, 0 ) ,
				new mss.SqlMetaData( "TheNumeric1", sd.SqlDbType.Decimal, 29, 28 ) ,
				new mss.SqlMetaData( "TheNumeric2", sd.SqlDbType.Decimal, 38, 1 ) 
			) ;
			 
			foreach ( var i in this._list ) 
			{
				if ( i.TheMoney == null )
					sdr.SetDBNull( 0 ) ;
				else
					sdr.SetDecimal( 0, i.TheMoney.Value ) ; 
			 
				if ( i.TheSmallMoney == null )
					sdr.SetDBNull( 1 ) ;
				else
					sdr.SetDecimal( 1, i.TheSmallMoney.Value ) ; 
			 
				if ( i.TheDecimal0 == null )
					sdr.SetDBNull( 2 ) ;
				else
					sdr.SetDecimal( 2, i.TheDecimal0.Value ) ; 
			 
				if ( i.TheDecimal1 == null )
					sdr.SetDBNull( 3 ) ;
				else
					sdr.SetDecimal( 3, i.TheDecimal1.Value ) ; 
			 
				if ( i.TheDecimal2 == null )
					sdr.SetDBNull( 4 ) ;
				else
					sdr.SetDecimal( 4, i.TheDecimal2.Value ) ; 
			 
				if ( i.TheNumeric0 == null )
					sdr.SetDBNull( 5 ) ;
				else
					sdr.SetDecimal( 5, i.TheNumeric0.Value ) ; 
			 
				if ( i.TheNumeric1 == null )
					sdr.SetDBNull( 6 ) ;
				else
					sdr.SetDecimal( 6, i.TheNumeric1.Value ) ; 
			 
				if ( i.TheNumeric2 == null )
					sdr.SetDBNull( 7 ) ;
				else
					sdr.SetDecimal( 7, i.TheNumeric2.Value ) ; 
			 
				yield return sdr ; 
			}
			 
		}

	}

}

