
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class MyVarmaxUnicodeTableType3٠ttlist : scg.List< MyVarmaxUnicodeTableType3٠tt >, scg.IEnumerable< mss.SqlDataRecord >
	{
		scg.List< MyVarmaxUnicodeTableType3٠tt > _list = null ;
		 
		public MyVarmaxUnicodeTableType3٠ttlist( scg.List< MyVarmaxUnicodeTableType3٠tt > list )
		{
			_list = list ;
		}
		 
		scg.IEnumerator< mss.SqlDataRecord > scg.IEnumerable< mss.SqlDataRecord >.GetEnumerator()
		{
			var sdr = new mss.SqlDataRecord
			(
				new mss.SqlMetaData( "MyChar", sd.SqlDbType.Char, 8000 ) 
			) ;
			 
			foreach ( var i in this._list ) 
			{
				if ( i.MyChar == null )
					sdr.SetDBNull( 0 ) ;
				else
					sdr.SetString( 0, i.MyChar ) ; 
			 
				yield return sdr ; 
			}
			 
		}

	}

}

