
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class MyVarmaxUnicodeTableType2٠tt : acr.RowBase
	{
		public const string column٠MyBinary  = "MyBinary" ;
		 
		public byte[] MyBinary
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠MyBinary ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠MyBinary, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public MyVarmaxUnicodeTableType2٠tt() : base()
		{
			base._dicˡ[ column٠MyBinary ] = null ;
		 
		}

	}

}

