
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class NameAddressTableType٠tt : acr.RowBase
	{
		public const string column٠Name  = "Name" ;
		public const string column٠Address  = "Address" ;
		public const string column٠State  = "State" ;
		 
		public string Name
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Name ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Name, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Address
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Address ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Address, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string State
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠State ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠State, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public NameAddressTableType٠tt() : base()
		{
			base._dicˡ[ column٠Name ] = null ;
			base._dicˡ[ column٠Address ] = null ;
			base._dicˡ[ column٠State ] = null ;
		 
		}

	}

}

