
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class Sales_by_Year٠rs1 : acr.RowBase
	{
		public const string column٠ShippedDate  = "ShippedDate" ;
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠Subtotal  = "Subtotal" ;
		public const string column٠Year  = "Year" ;
		 
		public DateTime? ShippedDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Subtotal
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Subtotal ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Subtotal, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Year
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Year ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Year, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Sales_by_Year٠rs1() : base()
		{
			base._dicˡ[ column٠ShippedDate ] = null ;
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠Subtotal ] = null ;
			base._dicˡ[ column٠Year ] = null ;
		 
		}

	}

}

