
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class sp_helpdiagrams٠rs1 : acr.RowBase
	{
		public const string column٠Database  = "Database" ;
		public const string column٠Name  = "Name" ;
		public const string column٠ID  = "ID" ;
		public const string column٠Owner  = "Owner" ;
		public const string column٠OwnerID  = "OwnerID" ;
		 
		public string Database
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Database ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Database, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Name
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Name ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Name, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Owner
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Owner ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Owner, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? OwnerID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OwnerID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OwnerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public sp_helpdiagrams٠rs1() : base()
		{
			base._dicˡ[ column٠Database ] = null ;
			base._dicˡ[ column٠Name ] = null ;
			base._dicˡ[ column٠ID ] = null ;
			base._dicˡ[ column٠Owner ] = null ;
			base._dicˡ[ column٠OwnerID ] = null ;
		 
		}

	}

}

