
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.storedProcedure
{
	public partial class Ten_Most_Expensive_Products٠rs1 : acr.RowBase
	{
		public const string column٠TenMostExpensiveProducts  = "TenMostExpensiveProducts" ;
		public const string column٠UnitPrice  = "UnitPrice" ;
		 
		public string TenMostExpensiveProducts
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TenMostExpensiveProducts ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TenMostExpensiveProducts, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? UnitPrice
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠UnitPrice ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠UnitPrice, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Ten_Most_Expensive_Products٠rs1() : base()
		{
			base._dicˡ[ column٠TenMostExpensiveProducts ] = null ;
			base._dicˡ[ column٠UnitPrice ] = null ;
		 
		}

	}

}

