
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.query
{
	public partial class CustomerOrderFactory : acr.FactoryBase< CustomerOrder, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static CustomerOrderFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_selectˡ = "alby.northwind.codegen.query.sql.CustomerOrder.Select.sql" ;
		}

		public scg.List<CustomerOrder> Load
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadAll.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerOrder> LoadByCustomer
		(
			sds.SqlConnection connˡ,
			string customerId,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@customerId", customerId );
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadByCustomer.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerOrder> LoadByRegion
		(
			sds.SqlConnection connˡ,
			string region,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@region", region );
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadByRegion.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerOrder> LoadByCustomerIdEmployeeIdOrderDateFreight
		(
			sds.SqlConnection connˡ,
			string customerId,
			int? employeeId,
			DateTime? orderDate,
			decimal? freight,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@customerId", customerId );
			base.AddParameterˡ( parametersˡ, "@employeeId", employeeId );
			base.AddParameterˡ( parametersˡ, "@orderDate", orderDate );
			base.AddParameterˡ( parametersˡ, "@freight", freight );
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadByCustomerIdEmployeeIdOrderDateFreight.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerOrder> LoadByShippedDate
		(
			sds.SqlConnection connˡ,
			DateTime? shippedDate,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@shippedDate", shippedDate );
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadByShippedDate.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerOrder> LoadByTerritory
		(
			sds.SqlConnection connˡ,
			string territoryDescription,
			int? orderYear,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@territoryDescription", territoryDescription );
			base.AddParameterˡ( parametersˡ, "@orderYear", orderYear );
			string whereˡ = "alby.northwind.codegen.query.sql.CustomerOrder.LoadByTerritory.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

