
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.query
{
	public partial class TestQuery01Factory : acr.FactoryBase< TestQuery01, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static TestQuery01Factory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_selectˡ = "alby.northwind.codegen.query.sql.TestQuery01.Select.sql" ;
		}

		public scg.List<TestQuery01> LoadByTheKey
		(
			sds.SqlConnection connˡ,
			int theKey,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@theKey", theKey );
			string whereˡ = "alby.northwind.codegen.query.sql.TestQuery01.LoadByTheKey.sql";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, true, whereˡ, true, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

