
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Categories : acr.RowBase
	{
		public const string column٠CategoryID  = "CategoryID" ;
		public const string column٠CategoryName  = "CategoryName" ;
		public const string column٠Description  = "Description" ;
		public const string column٠Picture  = "Picture" ;
		 
		public int? CategoryID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠CategoryID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠CategoryID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CategoryName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CategoryName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CategoryName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Description
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Description ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Description, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] Picture
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠Picture ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠Picture, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Categories() : base()
		{
			base._dicˡ[ column٠CategoryID ] = null ;
			base._dicˡ[ column٠CategoryName ] = null ;
			base._dicˡ[ column٠Description ] = null ;
			base._dicˡ[ column٠Picture ] = null ;
		 
			base._dicPKˡ[ column٠CategoryID ] = null ;
		 
		}

	}

}

