
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class CustomerDemographics : acr.RowBase
	{
		public scg.List<CustomerCustomerDemo> children٠CustomerCustomerDemo٠By٠CustomerTypeID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			CustomerCustomerDemoFactory factoryˡ = new CustomerCustomerDemoFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠CustomerDemographics٠By٠CustomerTypeID
			(
				connˡ,
				this.CustomerTypeID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

