
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.table
{
	public partial class CustomerCustomerDemoFactory : acr.FactoryBase< CustomerCustomerDemo, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static CustomerCustomerDemoFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "CustomerCustomerDemo" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [CustomerID], [CustomerTypeID] ) values ( @CustomerID, @CustomerTypeID ) " ;
			_insertIdentityˡ = "insert {0} ( [CustomerID], [CustomerTypeID] ) values ( @CustomerID, @CustomerTypeID ) " ;
			_updateˡ = "update {0} set [CustomerID] = @CustomerID, [CustomerTypeID] = @CustomerTypeID " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "where [CustomerID] = @pk_CustomerID and [CustomerTypeID] = @pk_CustomerTypeID " ;
			_whereSavePKˡ = "where [CustomerID] = @pk_CustomerID and [CustomerTypeID] = @pk_CustomerTypeID " ;
		}

		public CustomerCustomerDemo Saveˡ( sds.SqlConnection connˡ, CustomerCustomerDemo rowˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal, bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_CustomerID", rowˡ.PrimaryKeyDictionaryˡ[ CustomerCustomerDemo.column٠CustomerID ] );
			base.AddParameterˡ( parametersˡ, "@pk_CustomerTypeID", rowˡ.PrimaryKeyDictionaryˡ[ CustomerCustomerDemo.column٠CustomerTypeID ] );
			base.AddParameterˡ( parametersˡ, "@CustomerID", rowˡ.CustomerID, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@CustomerTypeID", rowˡ.CustomerTypeID, sd.SqlDbType.NText );

			int? identityIDˡ = null ;
			object objˡ = null ;
		 
			acr.SaveEnum saveResultˡ ;
		 
			if ( saveStrategyˡ != acr.CodeGenSaveStrategy.Normal )
			{
				saveResultˡ = base.ExecuteForceSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, saveStrategyˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereLoadPKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
			else
			{
				saveResultˡ = base.ExecuteSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereSavePKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
		 
			if ( saveResultˡ == acr.SaveEnum.Update ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.CustomerID, rowˡ.CustomerTypeID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Insert ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.CustomerID, rowˡ.CustomerTypeID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Delete )
				return null ;
			else
				return rowˡ ;
		}

		public scg.List<CustomerCustomerDemo> Saveˡ( sds.SqlConnection connˡ, scg.List<CustomerCustomerDemo> rowListˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal,  bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<CustomerCustomerDemo> rowList2ˡ = new scg.List<CustomerCustomerDemo>();
			foreach( CustomerCustomerDemo rowˡ in rowListˡ )
			{
				CustomerCustomerDemo row2ˡ = this.Saveˡ( connˡ, rowˡ, saveStrategyˡ, identityProvidedˡ, tranˡ ) ;
				if ( row2ˡ != null )	rowList2ˡ.Add( row2ˡ ) ;
			}
			return rowList2ˡ ;
		}

		public CustomerCustomerDemo LoadByPrimaryKeyˡ
		(
			sds.SqlConnection connˡ,
			string CustomerID,
			string CustomerTypeID,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_CustomerID", CustomerID );
			base.AddParameterˡ( parametersˡ, "@pk_CustomerTypeID", CustomerTypeID );
			return base.ExecuteQueryReturnOneˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, _whereLoadPKˡ, false ) ;
		}

		public scg.List<CustomerCustomerDemo> LoadByForeignKey٠From٠CustomerDemographics٠By٠CustomerTypeID
		(
			sds.SqlConnection connˡ,
			string CustomerTypeID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@CustomerTypeID", CustomerTypeID );
			string whereˡ = "where [CustomerTypeID] = @CustomerTypeID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerCustomerDemo> LoadByForeignKey٠From٠Customers٠By٠CustomerID
		(
			sds.SqlConnection connˡ,
			string CustomerID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@CustomerID", CustomerID );
			string whereˡ = "where [CustomerID] = @CustomerID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerCustomerDemo> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<CustomerCustomerDemo> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

