
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.table
{
	public partial class DatabaseVersionFactory : acr.FactoryBase< DatabaseVersion, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static DatabaseVersionFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "DatabaseVersion" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [DatabaseVersionID], [VersionText], [VersionFile], [UpdateUserName], [UpdateDateTime] ) values ( @DatabaseVersionID, @VersionText, @VersionFile, @UpdateUserName, @UpdateDateTime ) " ;
			_insertIdentityˡ = "insert {0} ( [DatabaseVersionID], [VersionText], [VersionFile], [UpdateUserName], [UpdateDateTime] ) values ( @DatabaseVersionID, @VersionText, @VersionFile, @UpdateUserName, @UpdateDateTime ) " ;
			_updateˡ = "update {0} set [DatabaseVersionID] = @DatabaseVersionID, [VersionText] = @VersionText, [VersionFile] = @VersionFile, [UpdateUserName] = @UpdateUserName, [UpdateDateTime] = @UpdateDateTime " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "where [DatabaseVersionID] = @pk_DatabaseVersionID " ;
			_whereSavePKˡ = "where [DatabaseVersionID] = @pk_DatabaseVersionID " ;
		}

		public DatabaseVersion Saveˡ( sds.SqlConnection connˡ, DatabaseVersion rowˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal, bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_DatabaseVersionID", rowˡ.PrimaryKeyDictionaryˡ[ DatabaseVersion.column٠DatabaseVersionID ] );
			base.AddParameterˡ( parametersˡ, "@DatabaseVersionID", rowˡ.DatabaseVersionID, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@VersionText", rowˡ.VersionText, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@VersionFile", rowˡ.VersionFile, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@UpdateUserName", rowˡ.UpdateUserName, sd.SqlDbType.NText );
			base.AddParameterˡ( parametersˡ, "@UpdateDateTime", rowˡ.UpdateDateTime, sd.SqlDbType.DateTime );
			base.AddParameterˡ( parametersˡ, "@UpdateTimetamp", rowˡ.UpdateTimetamp, sd.SqlDbType.Image );

			int? identityIDˡ = null ;
			object objˡ = null ;
		 
			acr.SaveEnum saveResultˡ ;
		 
			if ( saveStrategyˡ != acr.CodeGenSaveStrategy.Normal )
			{
				saveResultˡ = base.ExecuteForceSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, saveStrategyˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereLoadPKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
			else
			{
				saveResultˡ = base.ExecuteSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereSavePKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
		 
			if ( saveResultˡ == acr.SaveEnum.Update ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.DatabaseVersionID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Insert ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.DatabaseVersionID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Delete )
				return null ;
			else
				return rowˡ ;
		}

		public scg.List<DatabaseVersion> Saveˡ( sds.SqlConnection connˡ, scg.List<DatabaseVersion> rowListˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal,  bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<DatabaseVersion> rowList2ˡ = new scg.List<DatabaseVersion>();
			foreach( DatabaseVersion rowˡ in rowListˡ )
			{
				DatabaseVersion row2ˡ = this.Saveˡ( connˡ, rowˡ, saveStrategyˡ, identityProvidedˡ, tranˡ ) ;
				if ( row2ˡ != null )	rowList2ˡ.Add( row2ˡ ) ;
			}
			return rowList2ˡ ;
		}

		public DatabaseVersion LoadByPrimaryKeyˡ
		(
			sds.SqlConnection connˡ,
			int? DatabaseVersionID,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_DatabaseVersionID", DatabaseVersionID );
			return base.ExecuteQueryReturnOneˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, _whereLoadPKˡ, false ) ;
		}

		public scg.List<DatabaseVersion> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<DatabaseVersion> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

