
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class DatabaseVersion : acr.RowBase
	{
		public const string column٠DatabaseVersionID  = "DatabaseVersionID" ;
		public const string column٠VersionText  = "VersionText" ;
		public const string column٠VersionFile  = "VersionFile" ;
		public const string column٠UpdateUserName  = "UpdateUserName" ;
		public const string column٠UpdateDateTime  = "UpdateDateTime" ;
		public const string column٠UpdateTimetamp  = "UpdateTimetamp" ;
		 
		public int? DatabaseVersionID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠DatabaseVersionID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠DatabaseVersionID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string VersionText
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠VersionText ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠VersionText, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string VersionFile
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠VersionFile ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠VersionFile, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string UpdateUserName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠UpdateUserName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠UpdateUserName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? UpdateDateTime
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠UpdateDateTime, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] UpdateTimetamp
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠UpdateTimetamp ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠UpdateTimetamp, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DatabaseVersion() : base()
		{
			base._dicˡ[ column٠DatabaseVersionID ] = null ;
			base._dicˡ[ column٠VersionText ] = null ;
			base._dicˡ[ column٠VersionFile ] = null ;
			base._dicˡ[ column٠UpdateUserName ] = null ;
			base._dicˡ[ column٠UpdateDateTime ] = null ;
			base._dicˡ[ column٠UpdateTimetamp ] = null ;
		 
			base._dicPKˡ[ column٠DatabaseVersionID ] = null ;
		 
		}

	}

}

