
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Employees : acr.RowBase
	{
		public const string column٠EmployeeID  = "EmployeeID" ;
		public const string column٠LastName  = "LastName" ;
		public const string column٠FirstName  = "FirstName" ;
		public const string column٠Title  = "Title" ;
		public const string column٠TitleOfCourtesy  = "TitleOfCourtesy" ;
		public const string column٠BirthDate  = "BirthDate" ;
		public const string column٠HireDate  = "HireDate" ;
		public const string column٠Address  = "Address" ;
		public const string column٠City  = "City" ;
		public const string column٠Region  = "Region" ;
		public const string column٠PostalCode  = "PostalCode" ;
		public const string column٠Country  = "Country" ;
		public const string column٠HomePhone  = "HomePhone" ;
		public const string column٠Extension  = "Extension" ;
		public const string column٠Photo  = "Photo" ;
		public const string column٠Notes  = "Notes" ;
		public const string column٠ReportsTo  = "ReportsTo" ;
		public const string column٠PhotoPath  = "PhotoPath" ;
		 
		public int? EmployeeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠EmployeeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠EmployeeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string LastName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠LastName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠LastName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string FirstName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠FirstName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠FirstName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Title
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Title ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Title, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TitleOfCourtesy
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TitleOfCourtesy ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TitleOfCourtesy, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? BirthDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠BirthDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠BirthDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? HireDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠HireDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠HireDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Address
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Address ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Address, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string City
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠City ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠City, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Region
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Region ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Region, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PostalCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PostalCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PostalCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Country
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Country ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Country, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string HomePhone
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠HomePhone ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠HomePhone, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Extension
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Extension ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Extension, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] Photo
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠Photo ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠Photo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Notes
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Notes ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Notes, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ReportsTo
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ReportsTo ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ReportsTo, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PhotoPath
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PhotoPath ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PhotoPath, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Employees() : base()
		{
			base._dicˡ[ column٠EmployeeID ] = null ;
			base._dicˡ[ column٠LastName ] = null ;
			base._dicˡ[ column٠FirstName ] = null ;
			base._dicˡ[ column٠Title ] = null ;
			base._dicˡ[ column٠TitleOfCourtesy ] = null ;
			base._dicˡ[ column٠BirthDate ] = null ;
			base._dicˡ[ column٠HireDate ] = null ;
			base._dicˡ[ column٠Address ] = null ;
			base._dicˡ[ column٠City ] = null ;
			base._dicˡ[ column٠Region ] = null ;
			base._dicˡ[ column٠PostalCode ] = null ;
			base._dicˡ[ column٠Country ] = null ;
			base._dicˡ[ column٠HomePhone ] = null ;
			base._dicˡ[ column٠Extension ] = null ;
			base._dicˡ[ column٠Photo ] = null ;
			base._dicˡ[ column٠Notes ] = null ;
			base._dicˡ[ column٠ReportsTo ] = null ;
			base._dicˡ[ column٠PhotoPath ] = null ;
		 
			base._dicPKˡ[ column٠EmployeeID ] = null ;
		 
		}

	}

}

