
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.table
{
	public partial class EmployeeTerritoriesFactory : acr.FactoryBase< EmployeeTerritories, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static EmployeeTerritoriesFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "EmployeeTerritories" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [EmployeeID], [TerritoryID] ) values ( @EmployeeID, @TerritoryID ) " ;
			_insertIdentityˡ = "insert {0} ( [EmployeeID], [TerritoryID] ) values ( @EmployeeID, @TerritoryID ) " ;
			_updateˡ = "update {0} set [EmployeeID] = @EmployeeID, [TerritoryID] = @TerritoryID " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "where [EmployeeID] = @pk_EmployeeID and [TerritoryID] = @pk_TerritoryID " ;
			_whereSavePKˡ = "where [EmployeeID] = @pk_EmployeeID and [TerritoryID] = @pk_TerritoryID " ;
		}

		public EmployeeTerritories Saveˡ( sds.SqlConnection connˡ, EmployeeTerritories rowˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal, bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_EmployeeID", rowˡ.PrimaryKeyDictionaryˡ[ EmployeeTerritories.column٠EmployeeID ] );
			base.AddParameterˡ( parametersˡ, "@pk_TerritoryID", rowˡ.PrimaryKeyDictionaryˡ[ EmployeeTerritories.column٠TerritoryID ] );
			base.AddParameterˡ( parametersˡ, "@EmployeeID", rowˡ.EmployeeID, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@TerritoryID", rowˡ.TerritoryID, sd.SqlDbType.NText );

			int? identityIDˡ = null ;
			object objˡ = null ;
		 
			acr.SaveEnum saveResultˡ ;
		 
			if ( saveStrategyˡ != acr.CodeGenSaveStrategy.Normal )
			{
				saveResultˡ = base.ExecuteForceSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, saveStrategyˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereLoadPKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
			else
			{
				saveResultˡ = base.ExecuteSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereSavePKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
		 
			if ( saveResultˡ == acr.SaveEnum.Update ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.EmployeeID, rowˡ.TerritoryID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Insert ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.EmployeeID, rowˡ.TerritoryID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Delete )
				return null ;
			else
				return rowˡ ;
		}

		public scg.List<EmployeeTerritories> Saveˡ( sds.SqlConnection connˡ, scg.List<EmployeeTerritories> rowListˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal,  bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<EmployeeTerritories> rowList2ˡ = new scg.List<EmployeeTerritories>();
			foreach( EmployeeTerritories rowˡ in rowListˡ )
			{
				EmployeeTerritories row2ˡ = this.Saveˡ( connˡ, rowˡ, saveStrategyˡ, identityProvidedˡ, tranˡ ) ;
				if ( row2ˡ != null )	rowList2ˡ.Add( row2ˡ ) ;
			}
			return rowList2ˡ ;
		}

		public EmployeeTerritories LoadByPrimaryKeyˡ
		(
			sds.SqlConnection connˡ,
			int? EmployeeID,
			string TerritoryID,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_EmployeeID", EmployeeID );
			base.AddParameterˡ( parametersˡ, "@pk_TerritoryID", TerritoryID );
			return base.ExecuteQueryReturnOneˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, _whereLoadPKˡ, false ) ;
		}

		public scg.List<EmployeeTerritories> LoadByForeignKey٠From٠Employees٠By٠EmployeeID
		(
			sds.SqlConnection connˡ,
			int? EmployeeID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@EmployeeID", EmployeeID );
			string whereˡ = "where [EmployeeID] = @EmployeeID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<EmployeeTerritories> LoadByForeignKey٠From٠Territories٠By٠TerritoryID
		(
			sds.SqlConnection connˡ,
			string TerritoryID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@TerritoryID", TerritoryID );
			string whereˡ = "where [TerritoryID] = @TerritoryID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<EmployeeTerritories> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<EmployeeTerritories> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

