
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Employees : acr.RowBase
	{
		public Employees parent٠Employees٠By٠ReportsTo( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			EmployeesFactory factoryˡ = new EmployeesFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.ReportsTo, 
				tranˡ
			) ;
		}

		public scg.List<Employees> children٠Employees٠By٠ReportsTo( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			EmployeesFactory factoryˡ = new EmployeesFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Employees٠By٠ReportsTo
			(
				connˡ,
				this.EmployeeID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<EmployeeTerritories> children٠EmployeeTerritories٠By٠EmployeeID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			EmployeeTerritoriesFactory factoryˡ = new EmployeeTerritoriesFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Employees٠By٠EmployeeID
			(
				connˡ,
				this.EmployeeID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<Orders> children٠Orders٠By٠EmployeeID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			OrdersFactory factoryˡ = new OrdersFactory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Employees٠By٠EmployeeID
			(
				connˡ,
				this.EmployeeID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

		public scg.List<TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_> children٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_٠By٠EmployeeID( sds.SqlConnection connˡ, int? topNˡ = null, scg.List<acr.CodeGenOrderBy> orderByˡ = null, sds.SqlTransaction tranˡ = null )
		{
			TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_Factory factoryˡ = new TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_Factory() ; 
			return factoryˡ.LoadByForeignKey٠From٠Employees٠By٠EmployeeID
			(
				connˡ,
				this.EmployeeID, 
				topNˡ,
				orderByˡ,
				tranˡ
			) ;
		}

	}

}

