
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class EmployeeTerritories : acr.RowBase
	{
		public const string column٠EmployeeID  = "EmployeeID" ;
		public const string column٠TerritoryID  = "TerritoryID" ;
		 
		public int? EmployeeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠EmployeeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠EmployeeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TerritoryID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TerritoryID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TerritoryID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public EmployeeTerritories() : base()
		{
			base._dicˡ[ column٠EmployeeID ] = null ;
			base._dicˡ[ column٠TerritoryID ] = null ;
		 
			base._dicPKˡ[ column٠EmployeeID ] = null ;
			base._dicPKˡ[ column٠TerritoryID ] = null ;
		 
		}

	}

}

