
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Order_Details : acr.RowBase
	{
		public Orders parent٠Orders٠By٠OrderID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			OrdersFactory factoryˡ = new OrdersFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.OrderID, 
				tranˡ
			) ;
		}

		public Products parent٠Products٠By٠ProductID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			ProductsFactory factoryˡ = new ProductsFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.ProductID, 
				tranˡ
			) ;
		}

	}

}

