
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;
using ns = alby.northwind.codegen;

namespace alby.northwind.codegen.table
{
	public partial class Order_DetailsFactory : acr.FactoryBase< Order_Details, ns.database.NorthwindDatabaseSingletonHelper, ns.database.NorthwindDatabase >
	{
		static Order_DetailsFactory() 
		{
			_assemblyˡ = sr.Assembly.GetExecutingAssembly() ;
			_schemaˡ = "dbo" ;
			_tableˡ = "Order Details" ;
			_selectˡ = "select * from {0} t " ;
			_insertˡ = "insert {0} ( [OrderID], [ProductID], [UnitPrice], [Quantity], [Discount] ) values ( @OrderID, @ProductID, @UnitPrice, @Quantity, @Discount ) " ;
			_insertIdentityˡ = "insert {0} ( [OrderID], [ProductID], [UnitPrice], [Quantity], [Discount] ) values ( @OrderID, @ProductID, @UnitPrice, @Quantity, @Discount ) " ;
			_updateˡ = "update {0} set [OrderID] = @OrderID, [ProductID] = @ProductID, [UnitPrice] = @UnitPrice, [Quantity] = @Quantity, [Discount] = @Discount " ;
			_deleteˡ = "delete {0} " ;
			_whereLoadPKˡ = "where [OrderID] = @pk_OrderID and [ProductID] = @pk_ProductID " ;
			_whereSavePKˡ = "where [OrderID] = @pk_OrderID and [ProductID] = @pk_ProductID " ;
		}

		public Order_Details Saveˡ( sds.SqlConnection connˡ, Order_Details rowˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal, bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_OrderID", rowˡ.PrimaryKeyDictionaryˡ[ Order_Details.column٠OrderID ] );
			base.AddParameterˡ( parametersˡ, "@pk_ProductID", rowˡ.PrimaryKeyDictionaryˡ[ Order_Details.column٠ProductID ] );
			base.AddParameterˡ( parametersˡ, "@OrderID", rowˡ.OrderID, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@ProductID", rowˡ.ProductID, sd.SqlDbType.Int );
			base.AddParameterˡ( parametersˡ, "@UnitPrice", rowˡ.UnitPrice, sd.SqlDbType.Decimal );
			base.AddParameterˡ( parametersˡ, "@Quantity", rowˡ.Quantity, sd.SqlDbType.SmallInt );
			base.AddParameterˡ( parametersˡ, "@Discount", rowˡ.Discount, sd.SqlDbType.Real );

			int? identityIDˡ = null ;
			object objˡ = null ;
		 
			acr.SaveEnum saveResultˡ ;
		 
			if ( saveStrategyˡ != acr.CodeGenSaveStrategy.Normal )
			{
				saveResultˡ = base.ExecuteForceSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, saveStrategyˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereLoadPKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
			else
			{
				saveResultˡ = base.ExecuteSaveˡ( rowˡ, connˡ, tranˡ, parametersˡ, _insertˡ, _insertIdentityˡ, _updateˡ, _deleteˡ, _whereSavePKˡ, false, identityProvidedˡ, out objˡ ) ;
				if ( objˡ != null )
					identityIDˡ = int.Parse( objˡ.ToString() ) ;
			}
		 
			if ( saveResultˡ == acr.SaveEnum.Update ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.OrderID, rowˡ.ProductID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Insert ) 
				return this.LoadByPrimaryKeyˡ( connˡ, rowˡ.OrderID, rowˡ.ProductID, tranˡ ) ;
			else
			if ( saveResultˡ == acr.SaveEnum.Delete )
				return null ;
			else
				return rowˡ ;
		}

		public scg.List<Order_Details> Saveˡ( sds.SqlConnection connˡ, scg.List<Order_Details> rowListˡ, acr.CodeGenSaveStrategy saveStrategyˡ = acr.CodeGenSaveStrategy.Normal,  bool identityProvidedˡ = false, sds.SqlTransaction tranˡ = null )
		{
			scg.List<Order_Details> rowList2ˡ = new scg.List<Order_Details>();
			foreach( Order_Details rowˡ in rowListˡ )
			{
				Order_Details row2ˡ = this.Saveˡ( connˡ, rowˡ, saveStrategyˡ, identityProvidedˡ, tranˡ ) ;
				if ( row2ˡ != null )	rowList2ˡ.Add( row2ˡ ) ;
			}
			return rowList2ˡ ;
		}

		public Order_Details LoadByPrimaryKeyˡ
		(
			sds.SqlConnection connˡ,
			int? OrderID,
			int? ProductID,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@pk_OrderID", OrderID );
			base.AddParameterˡ( parametersˡ, "@pk_ProductID", ProductID );
			return base.ExecuteQueryReturnOneˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, _whereLoadPKˡ, false ) ;
		}

		public scg.List<Order_Details> LoadByForeignKey٠From٠Orders٠By٠OrderID
		(
			sds.SqlConnection connˡ,
			int? OrderID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@OrderID", OrderID );
			string whereˡ = "where [OrderID] = @OrderID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<Order_Details> LoadByForeignKey٠From٠Products٠By٠ProductID
		(
			sds.SqlConnection connˡ,
			int? ProductID,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			base.AddParameterˡ( parametersˡ, "@ProductID", ProductID );
			string whereˡ = "where [ProductID] = @ProductID " ; 
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<Order_Details> Loadˡ
		(
			sds.SqlConnection connˡ,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			scg.List<sds.SqlParameter> parametersˡ = new scg.List<sds.SqlParameter>();
			string whereˡ = "";
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

		public scg.List<Order_Details> LoadByWhereˡ
		(
			sds.SqlConnection connˡ,
			string whereˡ,
			scg.List<sds.SqlParameter> parametersˡ = null,
			int? topNˡ = null,
			scg.List<acr.CodeGenOrderBy> orderByˡ = null,
			sds.SqlTransaction tranˡ = null
		)
		{
			string sqlˡ = "" ; 
			return base.ExecuteQueryˡ( connˡ, tranˡ, parametersˡ, _assemblyˡ, _selectˡ, false, whereˡ, false, topNˡ, orderByˡ, out sqlˡ ) ;
		}

	}

}

