
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Orders : acr.RowBase
	{
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠CustomerID  = "CustomerID" ;
		public const string column٠EmployeeID  = "EmployeeID" ;
		public const string column٠OrderDate  = "OrderDate" ;
		public const string column٠RequiredDate  = "RequiredDate" ;
		public const string column٠ShippedDate  = "ShippedDate" ;
		public const string column٠ShipVia  = "ShipVia" ;
		public const string column٠Freight  = "Freight" ;
		public const string column٠ShipName  = "ShipName" ;
		public const string column٠ShipAddress  = "ShipAddress" ;
		public const string column٠ShipCity  = "ShipCity" ;
		public const string column٠ShipRegion  = "ShipRegion" ;
		public const string column٠ShipPostalCode  = "ShipPostalCode" ;
		public const string column٠ShipCountry  = "ShipCountry" ;
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CustomerID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? EmployeeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠EmployeeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠EmployeeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? OrderDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠OrderDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠OrderDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? RequiredDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠RequiredDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠RequiredDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? ShippedDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ShipVia
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ShipVia ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ShipVia, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Freight
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Freight ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Freight, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipAddress
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipAddress ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipAddress, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipCity
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipCity ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipCity, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipRegion
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipRegion ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipRegion, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipPostalCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipPostalCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipPostalCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipCountry
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipCountry ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipCountry, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Orders() : base()
		{
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠CustomerID ] = null ;
			base._dicˡ[ column٠EmployeeID ] = null ;
			base._dicˡ[ column٠OrderDate ] = null ;
			base._dicˡ[ column٠RequiredDate ] = null ;
			base._dicˡ[ column٠ShippedDate ] = null ;
			base._dicˡ[ column٠ShipVia ] = null ;
			base._dicˡ[ column٠Freight ] = null ;
			base._dicˡ[ column٠ShipName ] = null ;
			base._dicˡ[ column٠ShipAddress ] = null ;
			base._dicˡ[ column٠ShipCity ] = null ;
			base._dicˡ[ column٠ShipRegion ] = null ;
			base._dicˡ[ column٠ShipPostalCode ] = null ;
			base._dicˡ[ column٠ShipCountry ] = null ;
		 
			base._dicPKˡ[ column٠OrderID ] = null ;
		 
		}

	}

}

