
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Region : acr.RowBase
	{
		public const string column٠RegionID  = "RegionID" ;
		public const string column٠RegionDescription  = "RegionDescription" ;
		 
		public int? RegionID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠RegionID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠RegionID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string RegionDescription
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠RegionDescription ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠RegionDescription, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Region() : base()
		{
			base._dicˡ[ column٠RegionID ] = null ;
			base._dicˡ[ column٠RegionDescription ] = null ;
		 
			base._dicPKˡ[ column٠RegionID ] = null ;
		 
		}

	}

}

