
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Shippers : acr.RowBase
	{
		public const string column٠ShipperID  = "ShipperID" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠Phone  = "Phone" ;
		 
		public int? ShipperID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ShipperID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ShipperID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Phone
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Phone ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Phone, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Shippers() : base()
		{
			base._dicˡ[ column٠ShipperID ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠Phone ] = null ;
		 
			base._dicPKˡ[ column٠ShipperID ] = null ;
		 
		}

	}

}

