
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Suppliers : acr.RowBase
	{
		public const string column٠SupplierID  = "SupplierID" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠ContactName  = "ContactName" ;
		public const string column٠ContactTitle  = "ContactTitle" ;
		public const string column٠Address  = "Address" ;
		public const string column٠City  = "City" ;
		public const string column٠Region  = "Region" ;
		public const string column٠PostalCode  = "PostalCode" ;
		public const string column٠Country  = "Country" ;
		public const string column٠Phone  = "Phone" ;
		public const string column٠Fax  = "Fax" ;
		public const string column٠HomePage  = "HomePage" ;
		 
		public int? SupplierID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠SupplierID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠SupplierID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ContactName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ContactName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ContactName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ContactTitle
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ContactTitle ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ContactTitle, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Address
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Address ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Address, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string City
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠City ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠City, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Region
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Region ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Region, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PostalCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PostalCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PostalCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Country
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Country ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Country, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Phone
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Phone ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Phone, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Fax
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Fax ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Fax, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string HomePage
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠HomePage ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠HomePage, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Suppliers() : base()
		{
			base._dicˡ[ column٠SupplierID ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠ContactName ] = null ;
			base._dicˡ[ column٠ContactTitle ] = null ;
			base._dicˡ[ column٠Address ] = null ;
			base._dicˡ[ column٠City ] = null ;
			base._dicˡ[ column٠Region ] = null ;
			base._dicˡ[ column٠PostalCode ] = null ;
			base._dicˡ[ column٠Country ] = null ;
			base._dicˡ[ column٠Phone ] = null ;
			base._dicˡ[ column٠Fax ] = null ;
			base._dicˡ[ column٠HomePage ] = null ;
		 
			base._dicPKˡ[ column٠SupplierID ] = null ;
		 
		}

	}

}

