
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class sysdiagrams : acr.RowBase
	{
		public const string column٠name  = "name" ;
		public const string column٠principal_id  = "principal_id" ;
		public const string column٠diagram_id  = "diagram_id" ;
		public const string column٠version  = "version" ;
		public const string column٠definition  = "definition" ;
		 
		public string name
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠name ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠name, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? principal_id
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠principal_id ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠principal_id, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? diagram_id
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠diagram_id ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠diagram_id, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? version
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠version ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠version, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public byte[] definition
		{
			get
			{
				return base.GetValueˡ<byte[]>( _dicˡ, column٠definition ) ; 
			}
			set
			{
				base.SetValueˡ<byte[]>( _dicˡ, column٠definition, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public sysdiagrams() : base()
		{
			base._dicˡ[ column٠name ] = null ;
			base._dicˡ[ column٠principal_id ] = null ;
			base._dicˡ[ column٠diagram_id ] = null ;
			base._dicˡ[ column٠version ] = null ;
			base._dicˡ[ column٠definition ] = null ;
		 
			base._dicPKˡ[ column٠diagram_id ] = null ;
		 
		}

	}

}

