
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class Territories : acr.RowBase
	{
		public const string column٠TerritoryID  = "TerritoryID" ;
		public const string column٠TerritoryDescription  = "TerritoryDescription" ;
		public const string column٠RegionID  = "RegionID" ;
		 
		public string TerritoryID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TerritoryID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TerritoryID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TerritoryDescription
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TerritoryDescription ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TerritoryDescription, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? RegionID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠RegionID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠RegionID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Territories() : base()
		{
			base._dicˡ[ column٠TerritoryID ] = null ;
			base._dicˡ[ column٠TerritoryDescription ] = null ;
			base._dicˡ[ column٠RegionID ] = null ;
		 
			base._dicPKˡ[ column٠TerritoryID ] = null ;
		 
		}

	}

}

