
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable5 : acr.RowBase
	{
		public const string column٠ID  = "ID" ;
		public const string column٠f_int  = "f_int" ;
		public const string column٠f_nvarchar  = "f_nvarchar" ;
		public const string column٠update_date  = "update_date" ;
		 
		public int? ID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? f_int
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠f_int ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠f_int, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string f_nvarchar
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠f_nvarchar ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠f_nvarchar, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? update_date
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠update_date ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠update_date, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public TestTable5() : base()
		{
			base._dicˡ[ column٠ID ] = null ;
			base._dicˡ[ column٠f_int ] = null ;
			base._dicˡ[ column٠f_nvarchar ] = null ;
			base._dicˡ[ column٠update_date ] = null ;
		 
			base._dicPKˡ[ column٠ID ] = null ;
		 
			base.ConcurrencyColumnˡ = "update_date" ;
		}

	}

}

