
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable2b : acr.RowBase
	{
		public TestTable2a parent٠TestTable2a٠By٠HomeStateHomePostCode( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			TestTable2aFactory factoryˡ = new TestTable2aFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.HomeState, 
				this.HomePostCode, 
				tranˡ
			) ;
		}

		public TestTable2a parent٠TestTable2a٠By٠MailStateMailPostCode( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			TestTable2aFactory factoryˡ = new TestTable2aFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.MailState, 
				this.MailPostCode, 
				tranˡ
			) ;
		}

	}

}

