
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable2b : acr.RowBase
	{
		public const string column٠Person  = "Person" ;
		public const string column٠MailPostCode  = "MailPostCode" ;
		public const string column٠MailState  = "MailState" ;
		public const string column٠HomePostCode  = "HomePostCode" ;
		public const string column٠HomeState  = "HomeState" ;
		public const string column٠update_date  = "update_date" ;
		 
		public string Person
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Person ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Person, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string MailPostCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠MailPostCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠MailPostCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string MailState
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠MailState ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠MailState, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string HomePostCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠HomePostCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠HomePostCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string HomeState
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠HomeState ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠HomeState, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? update_date
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠update_date ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠update_date, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public TestTable2b() : base()
		{
			base._dicˡ[ column٠Person ] = null ;
			base._dicˡ[ column٠MailPostCode ] = null ;
			base._dicˡ[ column٠MailState ] = null ;
			base._dicˡ[ column٠HomePostCode ] = null ;
			base._dicˡ[ column٠HomeState ] = null ;
			base._dicˡ[ column٠update_date ] = null ;
		 
			base._dicPKˡ[ column٠Person ] = null ;
		 
			base.ConcurrencyColumnˡ = "update_date" ;
		}

	}

}

