
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable2a : acr.RowBase
	{
		public const string column٠State  = "State" ;
		public const string column٠PostCode  = "PostCode" ;
		public const string column٠Suburb  = "Suburb" ;
		public const string column٠update_date  = "update_date" ;
		 
		public string State
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠State ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠State, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PostCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PostCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PostCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Suburb
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Suburb ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Suburb, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? update_date
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠update_date ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠update_date, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public TestTable2a() : base()
		{
			base._dicˡ[ column٠State ] = null ;
			base._dicˡ[ column٠PostCode ] = null ;
			base._dicˡ[ column٠Suburb ] = null ;
			base._dicˡ[ column٠update_date ] = null ;
		 
			base._dicPKˡ[ column٠State ] = null ;
			base._dicPKˡ[ column٠PostCode ] = null ;
		 
			base.ConcurrencyColumnˡ = "update_date" ;
		}

	}

}

