
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ : acr.RowBase
	{
		public const string column٠ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_  = "ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒˇˈˊⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏۝" ;
		public const string column٠CategoryID  = "CategoryID" ;
		public const string column٠CustomerID  = "CustomerID" ;
		public const string column٠EmployeeID  = "EmployeeID" ;
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠ProductID  = "ProductID" ;
		public const string column٠RegionID  = "RegionID" ;
		public const string column٠ShipperID  = "ShipperID" ;
		public const string column٠SupplierID  = "SupplierID" ;
		public const string column٠TerritoryID  = "TerritoryID" ;
		public const string column٠update_date  = "update_date" ;
		 
		public int? ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? CategoryID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠CategoryID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠CategoryID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CustomerID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? EmployeeID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠EmployeeID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠EmployeeID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ProductID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ProductID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ProductID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? RegionID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠RegionID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠RegionID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ShipperID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ShipperID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ShipperID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? SupplierID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠SupplierID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠SupplierID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string TerritoryID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠TerritoryID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠TerritoryID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? update_date
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠update_date ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠update_date, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_() : base()
		{
			base._dicˡ[ column٠ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ] = null ;
			base._dicˡ[ column٠CategoryID ] = null ;
			base._dicˡ[ column٠CustomerID ] = null ;
			base._dicˡ[ column٠EmployeeID ] = null ;
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠ProductID ] = null ;
			base._dicˡ[ column٠RegionID ] = null ;
			base._dicˡ[ column٠ShipperID ] = null ;
			base._dicˡ[ column٠SupplierID ] = null ;
			base._dicˡ[ column٠TerritoryID ] = null ;
			base._dicˡ[ column٠update_date ] = null ;
		 
			base._dicPKˡ[ column٠ID_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ] = null ;
		 
			base.ConcurrencyColumnˡ = "update_date" ;
		}

	}

}

