
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ : acr.RowBase
	{
		public Categories parent٠Categories٠By٠CategoryID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			CategoriesFactory factoryˡ = new CategoriesFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.CategoryID, 
				tranˡ
			) ;
		}

		public Customers parent٠Customers٠By٠CustomerID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			CustomersFactory factoryˡ = new CustomersFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.CustomerID, 
				tranˡ
			) ;
		}

		public Employees parent٠Employees٠By٠EmployeeID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			EmployeesFactory factoryˡ = new EmployeesFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.EmployeeID, 
				tranˡ
			) ;
		}

		public Orders parent٠Orders٠By٠OrderID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			OrdersFactory factoryˡ = new OrdersFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.OrderID, 
				tranˡ
			) ;
		}

		public Products parent٠Products٠By٠ProductID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			ProductsFactory factoryˡ = new ProductsFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.ProductID, 
				tranˡ
			) ;
		}

		public Region parent٠Region٠By٠RegionID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			RegionFactory factoryˡ = new RegionFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.RegionID, 
				tranˡ
			) ;
		}

		public Shippers parent٠Shippers٠By٠ShipperID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			ShippersFactory factoryˡ = new ShippersFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.ShipperID, 
				tranˡ
			) ;
		}

		public Suppliers parent٠Suppliers٠By٠SupplierID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			SuppliersFactory factoryˡ = new SuppliersFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.SupplierID, 
				tranˡ
			) ;
		}

		public Territories parent٠Territories٠By٠TerritoryID( sds.SqlConnection connˡ, sds.SqlTransaction tranˡ = null )
		{
			TerritoriesFactory factoryˡ = new TerritoriesFactory() ; 
			return factoryˡ.LoadByPrimaryKeyˡ
			(
				connˡ,
				this.TerritoryID, 
				tranˡ
			) ;
		}

	}

}

