
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.table
{
	public partial class フル_ツ : acr.RowBase
	{
		public const string column٠フル_ツ_  = "フルーツ" ;
		public const string column٠fruit  = "fruit" ;
		public const string column٠פרי  = "פרי" ;
		public const string column٠καρπός  = "καρπός" ;
		public const string column٠update_date  = "update_date" ;
		 
		public string フル_ツ_
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠フル_ツ_ ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠フル_ツ_, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string fruit
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠fruit ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠fruit, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string פרי
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠פרי ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠פרי, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string καρπός
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠καρπός ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠καρπός, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? update_date
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠update_date ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠update_date, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public フル_ツ() : base()
		{
			base._dicˡ[ column٠フル_ツ_ ] = null ;
			base._dicˡ[ column٠fruit ] = null ;
			base._dicˡ[ column٠פרי ] = null ;
			base._dicˡ[ column٠καρπός ] = null ;
			base._dicˡ[ column٠update_date ] = null ;
		 
			base._dicPKˡ[ column٠フル_ツ_ ] = null ;
		 
			base.ConcurrencyColumnˡ = "update_date" ;
		}

	}

}

