
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠TestTable2a( bool insert, t.TestTable2a newobj, t.TestTable2a oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[10/24] TestTable2a - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.State, "TestTable2a.State" ) ;
			nu.Assert.IsNotNull( newobj.PostCode, "TestTable2a.PostCode" ) ;
			nu.Assert.IsNotNull( newobj.Suburb, "TestTable2a.Suburb" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "TestTable2a.update_date" ) ;
		 
			base.AssertAreEqual( newobj.State, oldobj.State, "TestTable2a.State" ) ;
			base.AssertAreEqual( newobj.PostCode, oldobj.PostCode, "TestTable2a.PostCode" ) ;
			base.AssertAreEqual( newobj.Suburb, oldobj.Suburb, "TestTable2a.Suburb" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "TestTable2a.update_date" ) ;
		 
		}
	}

}

