
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void AssertObjectsAfterUpdate()
		{
			// Categories
			this.Assert٠Categories( false, obj2٠Categories, obj1٠Categories ) ; 
			 
			// CustomerDemographics
			this.Assert٠CustomerDemographics( false, obj2٠CustomerDemographics, obj1٠CustomerDemographics ) ; 
			 
			// Customers
			this.Assert٠Customers( false, obj2٠Customers, obj1٠Customers ) ; 
			 
			// DatabaseVersion
			this.Assert٠DatabaseVersion( false, obj2٠DatabaseVersion, obj1٠DatabaseVersion ) ; 
			 
			// Region
			this.Assert٠Region( false, obj2٠Region, obj1٠Region ) ; 
			 
			// Shippers
			this.Assert٠Shippers( false, obj2٠Shippers, obj1٠Shippers ) ; 
			 
			// Suppliers
			this.Assert٠Suppliers( false, obj2٠Suppliers, obj1٠Suppliers ) ; 
			 
			// sysdiagrams
			this.Assert٠sysdiagrams( false, obj2٠sysdiagrams, obj1٠sysdiagrams ) ; 
			 
			// TestTable1
			this.Assert٠TestTable1( false, obj2٠TestTable1, obj1٠TestTable1 ) ; 
			 
			// TestTable2a
			this.Assert٠TestTable2a( false, obj2٠TestTable2a, obj1٠TestTable2a ) ; 
			 
			// TestTable3
			this.Assert٠TestTable3( false, obj2٠TestTable3, obj1٠TestTable3 ) ; 
			 
			// TestTable4
			this.Assert٠TestTable4( false, obj2٠TestTable4, obj1٠TestTable4 ) ; 
			 
			// TestTable5
			this.Assert٠TestTable5( false, obj2٠TestTable5, obj1٠TestTable5 ) ; 
			 
			// TestTable6a
			this.Assert٠TestTable6a( false, obj2٠TestTable6a, obj1٠TestTable6a ) ; 
			 
			// フル_ツ
			this.Assert٠フル_ツ( false, obj2٠フル_ツ, obj1٠フル_ツ ) ; 
			 
			// CustomerCustomerDemo
			this.Assert٠CustomerCustomerDemo( false, obj2٠CustomerCustomerDemo, obj1٠CustomerCustomerDemo ) ; 
			 
			// Employees
			this.Assert٠Employees( false, obj2٠Employees, obj1٠Employees ) ; 
			 
			// Orders
			this.Assert٠Orders( false, obj2٠Orders, obj1٠Orders ) ; 
			 
			// Products
			this.Assert٠Products( false, obj2٠Products, obj1٠Products ) ; 
			 
			// Order_Details
			this.Assert٠Order_Details( false, obj2٠Order_Details, obj1٠Order_Details ) ; 
			 
			// Territories
			this.Assert٠Territories( false, obj2٠Territories, obj1٠Territories ) ; 
			 
			// EmployeeTerritories
			this.Assert٠EmployeeTerritories( false, obj2٠EmployeeTerritories, obj1٠EmployeeTerritories ) ; 
			 
			// TestTable2b
			this.Assert٠TestTable2b( false, obj2٠TestTable2b, obj1٠TestTable2b ) ; 
			 
			// TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_
			this.Assert٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_( false, obj2٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_, obj1٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ) ; 
			 
		}
	}

}

