
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_( bool insert, t.TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ obj )
		{
			if ( insert )
			{
				// obj.CategoryID = null ;
				// obj.CustomerID = null ;
				// obj.EmployeeID = null ;
				// obj.OrderID = null ;
				// obj.ProductID = null ;
				// obj.RegionID = null ;
				// obj.ShipperID = null ;
				// obj.SupplierID = null ;
				// obj.TerritoryID = null ;
				// obj.update_date = null ;
			}
			else // update
			{
				// obj.CategoryID = null ;
				// obj.CustomerID = null ;
				// obj.EmployeeID = null ;
				// obj.OrderID = null ;
				// obj.ProductID = null ;
				// obj.RegionID = null ;
				// obj.ShipperID = null ;
				// obj.SupplierID = null ;
				// obj.TerritoryID = null ;
				// obj.update_date = null ;
			}
			 
		}
	}

}

