
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void AssertObjectsAfterInsert()
		{
			// Categories
			this.Assert٠Categories( true, obj1٠Categories, obj0٠Categories ) ; 
			 
			// CustomerDemographics
			this.Assert٠CustomerDemographics( true, obj1٠CustomerDemographics, obj0٠CustomerDemographics ) ; 
			 
			// Customers
			this.Assert٠Customers( true, obj1٠Customers, obj0٠Customers ) ; 
			 
			// DatabaseVersion
			this.Assert٠DatabaseVersion( true, obj1٠DatabaseVersion, obj0٠DatabaseVersion ) ; 
			 
			// Region
			this.Assert٠Region( true, obj1٠Region, obj0٠Region ) ; 
			 
			// Shippers
			this.Assert٠Shippers( true, obj1٠Shippers, obj0٠Shippers ) ; 
			 
			// Suppliers
			this.Assert٠Suppliers( true, obj1٠Suppliers, obj0٠Suppliers ) ; 
			 
			// sysdiagrams
			this.Assert٠sysdiagrams( true, obj1٠sysdiagrams, obj0٠sysdiagrams ) ; 
			 
			// TestTable1
			this.Assert٠TestTable1( true, obj1٠TestTable1, obj0٠TestTable1 ) ; 
			 
			// TestTable2a
			this.Assert٠TestTable2a( true, obj1٠TestTable2a, obj0٠TestTable2a ) ; 
			 
			// TestTable3
			this.Assert٠TestTable3( true, obj1٠TestTable3, obj0٠TestTable3 ) ; 
			 
			// TestTable4
			this.Assert٠TestTable4( true, obj1٠TestTable4, obj0٠TestTable4 ) ; 
			 
			// TestTable5
			this.Assert٠TestTable5( true, obj1٠TestTable5, obj0٠TestTable5 ) ; 
			 
			// TestTable6a
			this.Assert٠TestTable6a( true, obj1٠TestTable6a, obj0٠TestTable6a ) ; 
			 
			// フル_ツ
			this.Assert٠フル_ツ( true, obj1٠フル_ツ, obj0٠フル_ツ ) ; 
			 
			// CustomerCustomerDemo
			this.Assert٠CustomerCustomerDemo( true, obj1٠CustomerCustomerDemo, obj0٠CustomerCustomerDemo ) ; 
			 
			// Employees
			this.Assert٠Employees( true, obj1٠Employees, obj0٠Employees ) ; 
			 
			// Orders
			this.Assert٠Orders( true, obj1٠Orders, obj0٠Orders ) ; 
			 
			// Products
			this.Assert٠Products( true, obj1٠Products, obj0٠Products ) ; 
			 
			// Order_Details
			this.Assert٠Order_Details( true, obj1٠Order_Details, obj0٠Order_Details ) ; 
			 
			// Territories
			this.Assert٠Territories( true, obj1٠Territories, obj0٠Territories ) ; 
			 
			// EmployeeTerritories
			this.Assert٠EmployeeTerritories( true, obj1٠EmployeeTerritories, obj0٠EmployeeTerritories ) ; 
			 
			// TestTable2b
			this.Assert٠TestTable2b( true, obj1٠TestTable2b, obj0٠TestTable2b ) ; 
			 
			// TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_
			this.Assert٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_( true, obj1٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_, obj0٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ) ; 
			 
		}
	}

}

