
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠CustomerCustomerDemo( bool insert, t.CustomerCustomerDemo newobj, t.CustomerCustomerDemo oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[16/24] CustomerCustomerDemo - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.CustomerID, "CustomerCustomerDemo.CustomerID" ) ;
			nu.Assert.IsNotNull( newobj.CustomerTypeID, "CustomerCustomerDemo.CustomerTypeID" ) ;
		 
			base.AssertAreEqual( newobj.CustomerID, oldobj.CustomerID, "CustomerCustomerDemo.CustomerID" ) ;
			base.AssertAreEqual( newobj.CustomerTypeID, oldobj.CustomerTypeID, "CustomerCustomerDemo.CustomerTypeID" ) ;
		 
		}
	}

}

