
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠DatabaseVersion( bool insert, t.DatabaseVersion obj )
		{
			if ( insert )
			{
				obj.DatabaseVersionID = toint( factory٠DatabaseVersionFactory.GetNextIdˡ( _connection, t.DatabaseVersion.column٠DatabaseVersionID, true ).ToString() ) ;
				obj.VersionText = "@" ;
				obj.VersionFile = "@" ;
				obj.UpdateUserName = "@" ;
				obj.UpdateDateTime = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.VersionText = "#" ;
				obj.VersionFile = "#" ;
				obj.UpdateUserName = "#" ;
				obj.UpdateDateTime = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

