
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠Orders( bool insert, t.Orders obj )
		{
			if ( insert )
			{
				// obj.CustomerID = null ;
				// obj.EmployeeID = null ;
				// obj.OrderDate = null ;
				// obj.RequiredDate = null ;
				// obj.ShippedDate = null ;
				// obj.ShipVia = null ;
				// obj.Freight = null ;
				// obj.ShipName = null ;
				// obj.ShipAddress = null ;
				// obj.ShipCity = null ;
				// obj.ShipRegion = null ;
				// obj.ShipPostalCode = null ;
				// obj.ShipCountry = null ;
			}
			else // update
			{
				// obj.CustomerID = null ;
				// obj.EmployeeID = null ;
				// obj.OrderDate = null ;
				// obj.RequiredDate = null ;
				// obj.ShippedDate = null ;
				// obj.ShipVia = null ;
				// obj.Freight = null ;
				// obj.ShipName = null ;
				// obj.ShipAddress = null ;
				// obj.ShipCity = null ;
				// obj.ShipRegion = null ;
				// obj.ShipPostalCode = null ;
				// obj.ShipCountry = null ;
			}
			 
		}
	}

}

