
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void AssertObjectsNew()
		{
			// Categories
			this.AssertFlagsObjectNew( obj0٠Categories ) ; 
			 
			// CustomerDemographics
			this.AssertFlagsObjectNew( obj0٠CustomerDemographics ) ; 
			 
			// Customers
			this.AssertFlagsObjectNew( obj0٠Customers ) ; 
			 
			// DatabaseVersion
			this.AssertFlagsObjectNew( obj0٠DatabaseVersion ) ; 
			 
			// Region
			this.AssertFlagsObjectNew( obj0٠Region ) ; 
			 
			// Shippers
			this.AssertFlagsObjectNew( obj0٠Shippers ) ; 
			 
			// Suppliers
			this.AssertFlagsObjectNew( obj0٠Suppliers ) ; 
			 
			// sysdiagrams
			this.AssertFlagsObjectNew( obj0٠sysdiagrams ) ; 
			 
			// TestTable1
			this.AssertFlagsObjectNew( obj0٠TestTable1 ) ; 
			 
			// TestTable2a
			this.AssertFlagsObjectNew( obj0٠TestTable2a ) ; 
			 
			// TestTable3
			this.AssertFlagsObjectNew( obj0٠TestTable3 ) ; 
			 
			// TestTable4
			this.AssertFlagsObjectNew( obj0٠TestTable4 ) ; 
			 
			// TestTable5
			this.AssertFlagsObjectNew( obj0٠TestTable5 ) ; 
			 
			// TestTable6a
			this.AssertFlagsObjectNew( obj0٠TestTable6a ) ; 
			 
			// フル_ツ
			this.AssertFlagsObjectNew( obj0٠フル_ツ ) ; 
			 
			// CustomerCustomerDemo
			this.AssertFlagsObjectNew( obj0٠CustomerCustomerDemo ) ; 
			 
			// Employees
			this.AssertFlagsObjectNew( obj0٠Employees ) ; 
			 
			// Orders
			this.AssertFlagsObjectNew( obj0٠Orders ) ; 
			 
			// Products
			this.AssertFlagsObjectNew( obj0٠Products ) ; 
			 
			// Order_Details
			this.AssertFlagsObjectNew( obj0٠Order_Details ) ; 
			 
			// Territories
			this.AssertFlagsObjectNew( obj0٠Territories ) ; 
			 
			// EmployeeTerritories
			this.AssertFlagsObjectNew( obj0٠EmployeeTerritories ) ; 
			 
			// TestTable2b
			this.AssertFlagsObjectNew( obj0٠TestTable2b ) ; 
			 
			// TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_
			this.AssertFlagsObjectNew( obj0٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ ) ; 
			 
		}
	}

}

