
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠TestTable4( bool insert, t.TestTable4 obj )
		{
			if ( insert )
			{
				obj.ID = new Guid( "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" )  ;
				obj.f_guid = new Guid( "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa" )  ;
				obj.f_bigint = -100L ;
				obj.f_int = -100 ;
				obj.f_smallint = -100 ;
				obj.f_bit = true ;
				obj.f_decimal = -1.0m ;
				obj.f_numeric = -1.0m ;
				obj.f_money = -1.0m ;
				obj.f_smallmoney = -1.0m ;
				obj.f_float = -1.0d ;
				obj.f_real = -1.0f ;
				obj.f_datetime = new DateTime(1900,1,1) ;
				obj.f_smalldatetime = new DateTime(1900,1,1) ;
				obj.f_char = "@" ;
				obj.f_varchar = "@" ;
				obj.f_text = "@" ;
				obj.f_nchar = "@" ;
				obj.f_nvarchar = "@" ;
				obj.f_ntext = "@" ;
				obj.f_binary = new byte[] { 0x01 } ;
				obj.f_varbinary = new byte[] { 0x01 } ;
				obj.f_image = new byte[] { 0x01 } ;
				obj.f_xml = "@" ;
			}
			else // update
			{
				obj.f_guid = new Guid( "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb" )  ;
				obj.f_bigint = -200L ;
				obj.f_int = -200 ;
				obj.f_smallint = -200 ;
				obj.f_bit = false ;
				obj.f_decimal = -2.0m ;
				obj.f_numeric = -2.0m ;
				obj.f_money = -2.0m ;
				obj.f_smallmoney = -2.0m ;
				obj.f_float = -2.0d ;
				obj.f_real = -2.0f ;
				obj.f_datetime = new DateTime(1901,12,31) ;
				obj.f_smalldatetime = new DateTime(1901,12,31) ;
				obj.f_char = "#" ;
				obj.f_varchar = "#" ;
				obj.f_text = "#" ;
				obj.f_nchar = "#" ;
				obj.f_nvarchar = "#" ;
				obj.f_ntext = "#" ;
				obj.f_binary = new byte[] { 0x02 } ;
				obj.f_varbinary = new byte[] { 0x02 } ;
				obj.f_image = new byte[] { 0x02 } ;
				obj.f_xml = "#" ;
			}
			 
		}
	}

}

