
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Territories( bool insert, t.Territories newobj, t.Territories oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[21/24] Territories - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.TerritoryID, "Territories.TerritoryID" ) ;
			nu.Assert.IsNotNull( newobj.TerritoryDescription, "Territories.TerritoryDescription" ) ;
			nu.Assert.IsNotNull( newobj.RegionID, "Territories.RegionID" ) ;
		 
			base.AssertAreEqual( newobj.TerritoryID, oldobj.TerritoryID, "Territories.TerritoryID" ) ;
			base.AssertAreEqual( newobj.TerritoryDescription, oldobj.TerritoryDescription, "Territories.TerritoryDescription" ) ;
			base.AssertAreEqual( newobj.RegionID, oldobj.RegionID, "Territories.RegionID" ) ;
		 
		}
	}

}

