
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠フル_ツ( bool insert, t.フル_ツ newobj, t.フル_ツ oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[15/24] フル_ツ - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.フル_ツ_, "フル_ツ.フル_ツ_" ) ;
			nu.Assert.IsNotNull( newobj.fruit, "フル_ツ.fruit" ) ;
			nu.Assert.IsNotNull( newobj.פרי, "フル_ツ.פרי" ) ;
			nu.Assert.IsNotNull( newobj.καρπός, "フル_ツ.καρπός" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "フル_ツ.update_date" ) ;
		 
			base.AssertAreEqual( newobj.フル_ツ_, oldobj.フル_ツ_, "フル_ツ.フル_ツ_" ) ;
			base.AssertAreEqual( newobj.fruit, oldobj.fruit, "フル_ツ.fruit" ) ;
			base.AssertAreEqual( newobj.פרי, oldobj.פרי, "フル_ツ.פרי" ) ;
			base.AssertAreEqual( newobj.καρπός, oldobj.καρπός, "フル_ツ.καρπός" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "フル_ツ.update_date" ) ;
		 
		}
	}

}

