
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void PopulateOverride٠Employees( bool insert, t.Employees obj )
		{
			if ( insert )
			{
				// obj.LastName = null ;
				// obj.FirstName = null ;
				// obj.Title = null ;
				// obj.TitleOfCourtesy = null ;
				// obj.BirthDate = null ;
				// obj.HireDate = null ;
				// obj.Address = null ;
				// obj.City = null ;
				// obj.Region = null ;
				// obj.PostalCode = null ;
				// obj.Country = null ;
				// obj.HomePhone = null ;
				// obj.Extension = null ;
				// obj.Photo = null ;
				// obj.Notes = null ;
				// obj.ReportsTo = null ;
				// obj.PhotoPath = null ;
			}
			else // update
			{
				// obj.LastName = null ;
				// obj.FirstName = null ;
				// obj.Title = null ;
				// obj.TitleOfCourtesy = null ;
				// obj.BirthDate = null ;
				// obj.HireDate = null ;
				// obj.Address = null ;
				// obj.City = null ;
				// obj.Region = null ;
				// obj.PostalCode = null ;
				// obj.Country = null ;
				// obj.HomePhone = null ;
				// obj.Extension = null ;
				// obj.Photo = null ;
				// obj.Notes = null ;
				// obj.ReportsTo = null ;
				// obj.PhotoPath = null ;
			}
			 
		}
	}

}

