
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Employees( bool insert, t.Employees obj )
		{
			if ( insert )
			{
				obj.LastName = "@" ;
				obj.FirstName = "@" ;
				obj.Title = "@" ;
				obj.TitleOfCourtesy = "@" ;
				obj.BirthDate = new DateTime(1900,1,1) ;
				obj.HireDate = new DateTime(1900,1,1) ;
				obj.Address = "@" ;
				obj.City = "@" ;
				obj.Region = "@" ;
				obj.PostalCode = "@" ;
				obj.Country = "@" ;
				obj.HomePhone = "@" ;
				obj.Extension = "@" ;
				obj.Photo = new byte[] { 0x01 } ;
				obj.Notes = "@" ;
				obj.ReportsTo = obj1٠Employees != null ? obj1٠Employees.EmployeeID : obj0٠Employees.EmployeeID ;
				obj.PhotoPath = "@" ;
			}
			else // update
			{
				obj.LastName = "#" ;
				obj.FirstName = "#" ;
				obj.Title = "#" ;
				obj.TitleOfCourtesy = "#" ;
				obj.BirthDate = new DateTime(1901,12,31) ;
				obj.HireDate = new DateTime(1901,12,31) ;
				obj.Address = "#" ;
				obj.City = "#" ;
				obj.Region = "#" ;
				obj.PostalCode = "#" ;
				obj.Country = "#" ;
				obj.HomePhone = "#" ;
				obj.Extension = "#" ;
				obj.Photo = new byte[] { 0x02 } ;
				obj.Notes = "#" ;
				obj.PhotoPath = "#" ;
			}
			 
		}
	}

}

