
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠sysdiagrams( bool insert, t.sysdiagrams newobj, t.sysdiagrams oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[8/24] sysdiagrams - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.name, "sysdiagrams.name" ) ;
			nu.Assert.IsNotNull( newobj.principal_id, "sysdiagrams.principal_id" ) ;
			nu.Assert.IsNotNull( newobj.diagram_id, "sysdiagrams.diagram_id" ) ;
			nu.Assert.IsNotNull( newobj.version, "sysdiagrams.version" ) ;
			nu.Assert.IsNotNull( newobj.definition, "sysdiagrams.definition" ) ;
		 
			base.AssertAreEqual( newobj.name, oldobj.name, "sysdiagrams.name" ) ;
			base.AssertAreEqual( newobj.principal_id, oldobj.principal_id, "sysdiagrams.principal_id" ) ;
			base.AssertAreEqual( newobj.version, oldobj.version, "sysdiagrams.version" ) ;
			base.AssertAreEqual( newobj.definition, oldobj.definition, "sysdiagrams.definition" ) ;
		 
		}
	}

}

