
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Products( bool insert, t.Products obj )
		{
			if ( insert )
			{
				obj.ProductName = "@" ;
				obj.SupplierID = obj1٠Suppliers != null ? obj1٠Suppliers.SupplierID : obj0٠Suppliers.SupplierID ;
				obj.CategoryID = obj1٠Categories != null ? obj1٠Categories.CategoryID : obj0٠Categories.CategoryID ;
				obj.QuantityPerUnit = "@" ;
				obj.UnitPrice = -1.0m ;
				obj.UnitsInStock = -100 ;
				obj.UnitsOnOrder = -100 ;
				obj.ReorderLevel = -100 ;
				obj.Discontinued = true ;
			}
			else // update
			{
				obj.ProductName = "#" ;
				obj.QuantityPerUnit = "#" ;
				obj.UnitPrice = -2.0m ;
				obj.UnitsInStock = -200 ;
				obj.UnitsOnOrder = -200 ;
				obj.ReorderLevel = -200 ;
				obj.Discontinued = false ;
			}
			 
		}
	}

}

