
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠Suppliers( bool insert, t.Suppliers obj )
		{
			if ( insert )
			{
				obj.CompanyName = "@" ;
				obj.ContactName = "@" ;
				obj.ContactTitle = "@" ;
				obj.Address = "@" ;
				obj.City = "@" ;
				obj.Region = "@" ;
				obj.PostalCode = "@" ;
				obj.Country = "@" ;
				obj.Phone = "@" ;
				obj.Fax = "@" ;
				obj.HomePage = "@" ;
			}
			else // update
			{
				obj.CompanyName = "#" ;
				obj.ContactName = "#" ;
				obj.ContactTitle = "#" ;
				obj.Address = "#" ;
				obj.City = "#" ;
				obj.Region = "#" ;
				obj.PostalCode = "#" ;
				obj.Country = "#" ;
				obj.Phone = "#" ;
				obj.Fax = "#" ;
				obj.HomePage = "#" ;
			}
			 
		}
	}

}

