
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠TestTable2b( bool insert, t.TestTable2b newobj, t.TestTable2b oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[23/24] TestTable2b - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.Person, "TestTable2b.Person" ) ;
			nu.Assert.IsNotNull( newobj.MailPostCode, "TestTable2b.MailPostCode" ) ;
			nu.Assert.IsNotNull( newobj.MailState, "TestTable2b.MailState" ) ;
			nu.Assert.IsNotNull( newobj.HomePostCode, "TestTable2b.HomePostCode" ) ;
			nu.Assert.IsNotNull( newobj.HomeState, "TestTable2b.HomeState" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "TestTable2b.update_date" ) ;
		 
			base.AssertAreEqual( newobj.Person, oldobj.Person, "TestTable2b.Person" ) ;
			base.AssertAreEqual( newobj.MailPostCode, oldobj.MailPostCode, "TestTable2b.MailPostCode" ) ;
			base.AssertAreEqual( newobj.MailState, oldobj.MailState, "TestTable2b.MailState" ) ;
			base.AssertAreEqual( newobj.HomePostCode, oldobj.HomePostCode, "TestTable2b.HomePostCode" ) ;
			base.AssertAreEqual( newobj.HomeState, oldobj.HomeState, "TestTable2b.HomeState" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "TestTable2b.update_date" ) ;
		 
		}
	}

}

