
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠TestTable1( bool insert, t.TestTable1 obj )
		{
			if ( insert )
			{
				obj.The_Key = toint( factory٠TestTable1Factory.GetNextIdˡ( _connection, t.TestTable1.column٠The_Key, true ).ToString() ) ;
				obj.The_Value = "@" ;
				obj.update_date = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.The_Value = "#" ;
				obj.update_date = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

