
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Populate٠TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_( bool insert, t.TestTable7Unicode_ẻẽếℚℛℜᾈᾉᾊᄐᄑᄒ___ⅠⅡⅢⅴⅵⅶɑ̀ɒ́ɑ̂ािी०१२︳︴﹍﹎﹏_ obj )
		{
			if ( insert )
			{
				obj.CategoryID = obj1٠Categories != null ? obj1٠Categories.CategoryID : obj0٠Categories.CategoryID ;
				obj.CustomerID = obj1٠Customers != null ? obj1٠Customers.CustomerID : obj0٠Customers.CustomerID ;
				obj.EmployeeID = obj1٠Employees != null ? obj1٠Employees.EmployeeID : obj0٠Employees.EmployeeID ;
				obj.OrderID = obj1٠Orders != null ? obj1٠Orders.OrderID : obj0٠Orders.OrderID ;
				obj.ProductID = obj1٠Products != null ? obj1٠Products.ProductID : obj0٠Products.ProductID ;
				obj.RegionID = obj1٠Region != null ? obj1٠Region.RegionID : obj0٠Region.RegionID ;
				obj.ShipperID = obj1٠Shippers != null ? obj1٠Shippers.ShipperID : obj0٠Shippers.ShipperID ;
				obj.SupplierID = obj1٠Suppliers != null ? obj1٠Suppliers.SupplierID : obj0٠Suppliers.SupplierID ;
				obj.TerritoryID = obj1٠Territories != null ? obj1٠Territories.TerritoryID : obj0٠Territories.TerritoryID ;
				obj.update_date = new DateTime(1900,1,1) ;
			}
			else // update
			{
				obj.update_date = new DateTime(1901,12,31) ;
			}
			 
		}
	}

}

