
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Shippers( bool insert, t.Shippers newobj, t.Shippers oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[6/24] Shippers - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.ShipperID, "Shippers.ShipperID" ) ;
			nu.Assert.IsNotNull( newobj.CompanyName, "Shippers.CompanyName" ) ;
			nu.Assert.IsNotNull( newobj.Phone, "Shippers.Phone" ) ;
		 
			base.AssertAreEqual( newobj.CompanyName, oldobj.CompanyName, "Shippers.CompanyName" ) ;
			base.AssertAreEqual( newobj.Phone, oldobj.Phone, "Shippers.Phone" ) ;
		 
		}
	}

}

