
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠Customers( bool insert, t.Customers newobj, t.Customers oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[3/24] Customers - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.CustomerID, "Customers.CustomerID" ) ;
			nu.Assert.IsNotNull( newobj.CompanyName, "Customers.CompanyName" ) ;
			nu.Assert.IsNotNull( newobj.ContactName, "Customers.ContactName" ) ;
			nu.Assert.IsNotNull( newobj.ContactTitle, "Customers.ContactTitle" ) ;
			nu.Assert.IsNotNull( newobj.Address, "Customers.Address" ) ;
			nu.Assert.IsNotNull( newobj.City, "Customers.City" ) ;
			nu.Assert.IsNotNull( newobj.Region, "Customers.Region" ) ;
			nu.Assert.IsNotNull( newobj.PostalCode, "Customers.PostalCode" ) ;
			nu.Assert.IsNotNull( newobj.Country, "Customers.Country" ) ;
			nu.Assert.IsNotNull( newobj.Phone, "Customers.Phone" ) ;
			nu.Assert.IsNotNull( newobj.Fax, "Customers.Fax" ) ;
		 
			base.AssertAreEqual( newobj.CustomerID, oldobj.CustomerID, "Customers.CustomerID" ) ;
			base.AssertAreEqual( newobj.CompanyName, oldobj.CompanyName, "Customers.CompanyName" ) ;
			base.AssertAreEqual( newobj.ContactName, oldobj.ContactName, "Customers.ContactName" ) ;
			base.AssertAreEqual( newobj.ContactTitle, oldobj.ContactTitle, "Customers.ContactTitle" ) ;
			base.AssertAreEqual( newobj.Address, oldobj.Address, "Customers.Address" ) ;
			base.AssertAreEqual( newobj.City, oldobj.City, "Customers.City" ) ;
			base.AssertAreEqual( newobj.Region, oldobj.Region, "Customers.Region" ) ;
			base.AssertAreEqual( newobj.PostalCode, oldobj.PostalCode, "Customers.PostalCode" ) ;
			base.AssertAreEqual( newobj.Country, oldobj.Country, "Customers.Country" ) ;
			base.AssertAreEqual( newobj.Phone, oldobj.Phone, "Customers.Phone" ) ;
			base.AssertAreEqual( newobj.Fax, oldobj.Fax, "Customers.Fax" ) ;
		 
		}
	}

}

