
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠TestTable6a( bool insert, t.TestTable6a newobj, t.TestTable6a oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[14/24] TestTable6a - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.ID, "TestTable6a.ID" ) ;
			nu.Assert.IsNotNull( newobj.Name, "TestTable6a.Name" ) ;
			nu.Assert.IsNotNull( newobj.Age, "TestTable6a.Age" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "TestTable6a.update_date" ) ;
		 
			base.AssertAreEqual( newobj.ID, oldobj.ID, "TestTable6a.ID" ) ;
			base.AssertAreEqual( newobj.Name, oldobj.Name, "TestTable6a.Name" ) ;
			base.AssertAreEqual( newobj.Age, oldobj.Age, "TestTable6a.Age" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "TestTable6a.update_date" ) ;
		 
		}
	}

}

