
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠TestTable1( bool insert, t.TestTable1 newobj, t.TestTable1 oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[9/24] TestTable1 - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.The_Key, "TestTable1.The_Key" ) ;
			nu.Assert.IsNotNull( newobj.The_Value, "TestTable1.The_Value" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "TestTable1.update_date" ) ;
		 
			base.AssertAreEqual( newobj.The_Key, oldobj.The_Key, "TestTable1.The_Key" ) ;
			base.AssertAreEqual( newobj.The_Value, oldobj.The_Value, "TestTable1.The_Value" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "TestTable1.update_date" ) ;
		 
		}
	}

}

