
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

using nu = NUnit.Framework;
using t = alby.northwind.codegen.table ;

namespace alby.northwind.codegen.test
{
	public partial class CodeGenUnitTestClass : acr.CodeGenUnitTestBase
	{
		protected void Assert٠TestTable3( bool insert, t.TestTable3 newobj, t.TestTable3 oldobj )
		{
			acr.CodeGenEtc.ConsoleMessage( ! this.QuietMode, "[11/24] TestTable3 - assert" ) ;
		 
			nu.Assert.IsNotNull( newobj.ID, "TestTable3.ID" ) ;
			nu.Assert.IsNotNull( newobj.A, "TestTable3.A" ) ;
			nu.Assert.IsNotNull( newobj.B, "TestTable3.B" ) ;
			nu.Assert.IsNotNull( newobj.C, "TestTable3.C" ) ;
			nu.Assert.IsNotNull( newobj.TheSum, "TestTable3.TheSum" ) ;
			nu.Assert.IsNotNull( newobj.TheProduct, "TestTable3.TheProduct" ) ;
			nu.Assert.IsNotNull( newobj.update_date, "TestTable3.update_date" ) ;
		 
			base.AssertAreEqual( newobj.ID, oldobj.ID, "TestTable3.ID" ) ;
			base.AssertAreEqual( newobj.A, oldobj.A, "TestTable3.A" ) ;
			base.AssertAreEqual( newobj.B, oldobj.B, "TestTable3.B" ) ;
			base.AssertAreEqual( newobj.C, oldobj.C, "TestTable3.C" ) ;
			base.AssertAreEqual( newobj.update_date, oldobj.update_date, "TestTable3.update_date" ) ;
		 
		}
	}

}

