
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Category_Sales_for_1997 : acr.RowBase
	{
		public const string column٠CategoryName  = "CategoryName" ;
		public const string column٠CategorySales  = "CategorySales" ;
		 
		public string CategoryName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CategoryName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CategoryName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? CategorySales
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠CategorySales ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠CategorySales, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Category_Sales_for_1997() : base()
		{
			base._dicˡ[ column٠CategoryName ] = null ;
			base._dicˡ[ column٠CategorySales ] = null ;
		 
		 
		}

	}

}

