
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Customer_and_Suppliers_by_City : acr.RowBase
	{
		public const string column٠City  = "City" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠ContactName  = "ContactName" ;
		public const string column٠Relationship  = "Relationship" ;
		 
		public string City
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠City ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠City, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ContactName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ContactName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ContactName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Relationship
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Relationship ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Relationship, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Customer_and_Suppliers_by_City() : base()
		{
			base._dicˡ[ column٠City ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠ContactName ] = null ;
			base._dicˡ[ column٠Relationship ] = null ;
		 
		 
		}

	}

}

