
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Invoices : acr.RowBase
	{
		public const string column٠ShipName  = "ShipName" ;
		public const string column٠ShipAddress  = "ShipAddress" ;
		public const string column٠ShipCity  = "ShipCity" ;
		public const string column٠ShipRegion  = "ShipRegion" ;
		public const string column٠ShipPostalCode  = "ShipPostalCode" ;
		public const string column٠ShipCountry  = "ShipCountry" ;
		public const string column٠CustomerID  = "CustomerID" ;
		public const string column٠CustomerName  = "CustomerName" ;
		public const string column٠Address  = "Address" ;
		public const string column٠City  = "City" ;
		public const string column٠Region  = "Region" ;
		public const string column٠PostalCode  = "PostalCode" ;
		public const string column٠Country  = "Country" ;
		public const string column٠Salesperson  = "Salesperson" ;
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠OrderDate  = "OrderDate" ;
		public const string column٠RequiredDate  = "RequiredDate" ;
		public const string column٠ShippedDate  = "ShippedDate" ;
		public const string column٠ShipperName  = "ShipperName" ;
		public const string column٠ProductID  = "ProductID" ;
		public const string column٠ProductName  = "ProductName" ;
		public const string column٠UnitPrice  = "UnitPrice" ;
		public const string column٠Quantity  = "Quantity" ;
		public const string column٠Discount  = "Discount" ;
		public const string column٠ExtendedPrice  = "ExtendedPrice" ;
		public const string column٠Freight  = "Freight" ;
		 
		public string ShipName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipAddress
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipAddress ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipAddress, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipCity
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipCity ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipCity, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipRegion
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipRegion ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipRegion, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipPostalCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipPostalCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipPostalCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipCountry
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipCountry ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipCountry, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CustomerID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CustomerName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Address
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Address ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Address, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string City
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠City ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠City, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Region
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Region ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Region, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string PostalCode
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠PostalCode ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠PostalCode, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Country
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Country ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Country, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Salesperson
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Salesperson ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Salesperson, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? OrderDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠OrderDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠OrderDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? RequiredDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠RequiredDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠RequiredDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? ShippedDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ShipperName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ShipperName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ShipperName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? ProductID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠ProductID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠ProductID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string ProductName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠ProductName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠ProductName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? UnitPrice
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠UnitPrice ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠UnitPrice, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public short? Quantity
		{
			get
			{
				return base.GetValueˡ<short?>( _dicˡ, column٠Quantity ) ; 
			}
			set
			{
				base.SetValueˡ<short?>( _dicˡ, column٠Quantity, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public float? Discount
		{
			get
			{
				return base.GetValueˡ<float?>( _dicˡ, column٠Discount ) ; 
			}
			set
			{
				base.SetValueˡ<float?>( _dicˡ, column٠Discount, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? ExtendedPrice
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠ExtendedPrice ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠ExtendedPrice, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Freight
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Freight ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Freight, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Invoices() : base()
		{
			base._dicˡ[ column٠ShipName ] = null ;
			base._dicˡ[ column٠ShipAddress ] = null ;
			base._dicˡ[ column٠ShipCity ] = null ;
			base._dicˡ[ column٠ShipRegion ] = null ;
			base._dicˡ[ column٠ShipPostalCode ] = null ;
			base._dicˡ[ column٠ShipCountry ] = null ;
			base._dicˡ[ column٠CustomerID ] = null ;
			base._dicˡ[ column٠CustomerName ] = null ;
			base._dicˡ[ column٠Address ] = null ;
			base._dicˡ[ column٠City ] = null ;
			base._dicˡ[ column٠Region ] = null ;
			base._dicˡ[ column٠PostalCode ] = null ;
			base._dicˡ[ column٠Country ] = null ;
			base._dicˡ[ column٠Salesperson ] = null ;
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠OrderDate ] = null ;
			base._dicˡ[ column٠RequiredDate ] = null ;
			base._dicˡ[ column٠ShippedDate ] = null ;
			base._dicˡ[ column٠ShipperName ] = null ;
			base._dicˡ[ column٠ProductID ] = null ;
			base._dicˡ[ column٠ProductName ] = null ;
			base._dicˡ[ column٠UnitPrice ] = null ;
			base._dicˡ[ column٠Quantity ] = null ;
			base._dicˡ[ column٠Discount ] = null ;
			base._dicˡ[ column٠ExtendedPrice ] = null ;
			base._dicˡ[ column٠Freight ] = null ;
		 
		 
		}

	}

}

