
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Order_Subtotals : acr.RowBase
	{
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠Subtotal  = "Subtotal" ;
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public decimal? Subtotal
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠Subtotal ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠Subtotal, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Order_Subtotals() : base()
		{
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠Subtotal ] = null ;
		 
		 
		}

	}

}

