
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Quarterly_Orders : acr.RowBase
	{
		public const string column٠CustomerID  = "CustomerID" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠City  = "City" ;
		public const string column٠Country  = "Country" ;
		 
		public string CustomerID
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CustomerID ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CustomerID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string City
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠City ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠City, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string Country
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠Country ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠Country, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Quarterly_Orders() : base()
		{
			base._dicˡ[ column٠CustomerID ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠City ] = null ;
			base._dicˡ[ column٠Country ] = null ;
		 
		 
		}

	}

}

