
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class Sales_Totals_by_Amount : acr.RowBase
	{
		public const string column٠SaleAmount  = "SaleAmount" ;
		public const string column٠OrderID  = "OrderID" ;
		public const string column٠CompanyName  = "CompanyName" ;
		public const string column٠ShippedDate  = "ShippedDate" ;
		 
		public decimal? SaleAmount
		{
			get
			{
				return base.GetValueˡ<decimal?>( _dicˡ, column٠SaleAmount ) ; 
			}
			set
			{
				base.SetValueˡ<decimal?>( _dicˡ, column٠SaleAmount, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public int? OrderID
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠OrderID ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠OrderID, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string CompanyName
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠CompanyName ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠CompanyName, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public DateTime? ShippedDate
		{
			get
			{
				return base.GetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate ) ; 
			}
			set
			{
				base.SetValueˡ<DateTime?>( _dicˡ, column٠ShippedDate, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public Sales_Totals_by_Amount() : base()
		{
			base._dicˡ[ column٠SaleAmount ] = null ;
			base._dicˡ[ column٠OrderID ] = null ;
			base._dicˡ[ column٠CompanyName ] = null ;
			base._dicˡ[ column٠ShippedDate ] = null ;
		 
		 
		}

	}

}

