
// This file was automatically generated by the code gen tool - do not modify.

using System ;
using scg = System.Collections.Generic ;
using sd = System.Data ;
using sds = System.Data.SqlClient ;
using sr = System.Reflection ;
using mst = Microsoft.SqlServer.Types ;
using mss = Microsoft.SqlServer.Server ;
using acr = alby.codegen.runtime ;

namespace alby.northwind.codegen.view
{
	public partial class TestView1 : acr.RowBase
	{
		public const string column٠The_Key  = "The Key" ;
		public const string column٠The_Value  = "The Value" ;
		 
		public int? The_Key
		{
			get
			{
				return base.GetValueˡ<int?>( _dicˡ, column٠The_Key ) ; 
			}
			set
			{
				base.SetValueˡ<int?>( _dicˡ, column٠The_Key, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public string The_Value
		{
			get
			{
				return base.GetValueˡ<string>( _dicˡ, column٠The_Value ) ; 
			}
			set
			{
				base.SetValueˡ<string>( _dicˡ, column٠The_Value, value, ref _dirtyˡ ) ; 
			}
		}
		 
		public TestView1() : base()
		{
			base._dicˡ[ column٠The_Key ] = null ;
			base._dicˡ[ column٠The_Value ] = null ;
		 
		 
		}

	}

}

